FROM docker.io/bitnami/spark:2.4.6
MAINTAINER Vedant Kakade <vedantkakade.cp@gmail.com>

COPY jars/mysql-connector-java-8.0.26.jar /opt/bitnami/spark/jars/
COPY jars/mongo-spark-connector_2.11-2.4.2.jar /opt/bitnami/spark/jars/
COPY jars/mongodb-driver-3.8.1.jar /opt/bitnami/spark/jars/
COPY jars/mongodb-driver-core-3.8.1.jar /opt/bitnami/spark/jars/
COPY jars/bson-3.8.1.jar /opt/bitnami/spark/jars/
