version: "3"
services:
  mysql:
    image: "mysql"
    restart: always
    environment:
      MYSQL_USER: "spark-user"
      MYSQL_PASSWORD: "spark123"
      MYSQL_ROOT_PASSWORD: "root123"
    ports:
      - "3307:3307"
    expose:
      - "3307"
    volumes:
      - games-db:/var/lib/mysql
  
  mongo:
    image: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "spark-user"
      MONGO_INITDB_ROOT_PASSWORD: "spark123"
    ports:
      - "27018:27018"
    expose:
      - "27018"
    volumes:
      - games-db:/data/db
  
  spark:
    image: docker.io/bitnami/spark:3
    environment:
      SPARK_MODE: "master"
      SPARK_RPC_AUTHENTICATION_ENABLED: "no"
      SPARK_RPC_ENCRYPTION_ENABLED: "no"
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: "no"
      SPARK_SSL_ENABLED: "no"
    ports:
      - "8080:8080"
      - "7077:7077"
  
  spark-worker-1:
    image: docker.io/bitnami/spark:3
    user: root
    environment:
      SPARK_MODE: "worker"
      SPARK_MASTER_URL: "spark://spark:7077"
      SPARK_WORKER_MEMORY: "1G"
      SPARK_WORKER_CORES: 1
      SPARK_RPC_AUTHENTICATION_ENABLED: "no"
      SPARK_RPC_ENCRYPTION_ENABLED: "no"
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: "no"
      SPARK_SSL_ENABLED: "no"
    depends_on:
      - spark
    ports:
      - "8081:8081"

volumes:
  games-db: